/**
 * FILTERS
 *
 * PURPOSE:
 * Category filter buttons on /work/, /creatives/ and /design/.
 * Clicking a button hides every card that does not belong to
 * that category.
 *
 * HOW IT CONNECTS:
 *   <div data-filter-bar data-filter-target="work-grid">
 *       <button data-filter="all">All</button>
 *       <button data-filter="funnels">Funnels</button>
 *   </div>
 *   <div id="work-grid" data-filter-list>
 *       <article data-filter-item data-filter-values="funnels recruiting"> ...
 *   </div>
 *
 * The values come from "category" in each project.json
 * (written in lower case). Generated by /frontend/build/renderers/.
 *
 * The chosen filter is kept in the URL (?filter=recruiting), so a
 * filtered view can be shared as a link.
 */

import { prefersReducedMotion } from "./motion.js";

export function initFilters() {
    document.querySelectorAll("[data-filter-bar]").forEach(setupFilterBar);
}

function setupFilterBar(bar) {
    const list = document.getElementById(bar.dataset.filterTarget);
    if (!list) {
        console.error(`[FILTERS] No list with id "${bar.dataset.filterTarget}" found. Module: scripts/modules/filters.js`);
        return;
    }

    const buttons = [...bar.querySelectorAll("[data-filter]")];
    const items = [...list.querySelectorAll("[data-filter-item]")];
    const emptyMessage = list.parentElement.querySelector("[data-filter-empty]");

    const apply = (value, { updateUrl = true } = {}) => {
        let visible = 0;

        for (const item of items) {
            const values = (item.dataset.filterValues || "").split(" ");
            const matches = value === "all" || values.includes(value);
            item.classList.toggle("is-filtered-out", !matches);
            item.classList.remove("is-filter-entering");
            if (matches) {
                visible += 1;
                if (!prefersReducedMotion()) {
                    void item.offsetWidth; // restart the CSS animation
                    item.classList.add("is-filter-entering");
                }
                // Cards revealed while hidden would otherwise stay invisible
                item.querySelectorAll("[data-reveal]").forEach((element) => element.classList.add("is-revealed"));
            }
        }

        buttons.forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.filter === value)));
        if (emptyMessage) emptyMessage.hidden = visible > 0;

        if (updateUrl) {
            const url = new URL(window.location.href);
            value === "all" ? url.searchParams.delete("filter") : url.searchParams.set("filter", value);
            history.replaceState(null, "", url);
        }
    };

    buttons.forEach((button) => button.addEventListener("click", () => apply(button.dataset.filter)));

    // Filter from the URL, e.g. /creatives/?filter=recruiting
    const fromUrl = new URL(window.location.href).searchParams.get("filter");
    if (fromUrl && buttons.some((button) => button.dataset.filter === fromUrl)) {
        apply(fromUrl, { updateUrl: false });
    }
}
